# Generated by Django 2.0 on 2018-02-10 20:07

from django.db import migrations, models
import webstore.cash.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherCourierPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cbm', models.FloatField()),
                ('price', webstore.cash.fields.CashField(max_length=32)),
            ],
            options={
                'ordering': ['max_cbm'],
            },
        ),
        migrations.CreateModel(
            name='SomeCourierPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.FloatField(unique=True)),
                ('price', webstore.cash.fields.CashField(max_length=32)),
            ],
            options={
                'ordering': ['max_weight'],
            },
        ),
    ]
