# Generated by Django 2.1.3 on 2018-11-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('surname', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('postal_code', models.CharField(max_length=16, null=True)),
                ('street_name', models.CharField(max_length=64)),
                ('street_number', models.CharField(max_length=16)),
                ('flat_number', models.CharField(max_length=16, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
