# Generated by Django 2.0.2 on 2018-08-12 13:17

from django.db import migrations, models
import django.db.models.deletion
import webstore.cash.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('surname', models.CharField(max_length=64, null=True)),
                ('street_name', models.CharField(max_length=64)),
                ('street_number', models.CharField(max_length=16)),
                ('flat_number', models.CharField(max_length=16, null=True)),
                ('cost', webstore.cash.fields.CashField(max_length=32)),
                ('status', models.CharField(choices=[('READY_FOR_SHIPPING', 'ready for shipping'), ('SHIPPED', 'shipped')], default='AWAITING_PAYMENT', max_length=32)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='order.Order')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cost_per_kg', webstore.cash.fields.CashField(max_length=32)),
            ],
        ),
    ]
