# Generated by Django 2.0.2 on 2018-02-16 23:02

from django.db import migrations, models
import django.db.models.deletion
import webstore.cash.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('param', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_param', models.FloatField(unique=True)),
                ('price', webstore.cash.fields.CashField(max_length=32)),
                ('delivery_option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.DeliveryOption')),
            ],
            options={
                'ordering': ['delivery_option', 'max_param'],
            },
        ),
        migrations.DeleteModel(
            name='AnotherCourierPricing',
        ),
        migrations.DeleteModel(
            name='SomeCourierPricing',
        ),
    ]
