# Generated by Django 2.0 on 2018-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20181117_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
