# Generated by Django 2.0.2 on 2018-02-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20180216_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypricing',
            name='max_param',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='deliverypricing',
            unique_together={('delivery_option', 'max_param')},
        ),
    ]
