# Generated by Django 2.0.2 on 2018-02-17 21:11

from django.db import migrations, models
import django.db.models.deletion
import webstore.cash.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180205_2156'),
        ('delivery', '0003_auto_20180216_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', webstore.cash.fields.CashField(max_length=32)),
                ('delivery_option', models.ForeignKey(on_delete=models.SET('0'), to='delivery.DeliveryOption')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
