# Generated by Django 2.1.3 on 2018-12-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20181117_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypricing',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
