# Generated by Django 2.0 on 2018-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20181117_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ('created',), 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
