# Generated by Django 2.1.3 on 2019-01-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverypricing_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='modified',
            new_name='edited',
        ),
    ]
