# Generated by Django 2.0 on 2018-07-01 18:59

from django.db import migrations, models
import webstore.cash.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypricing',
            options={},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_option',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='value',
        ),
        migrations.AddField(
            model_name='delivery',
            name='flat_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=webstore.cash.fields.CashField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='street_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='street_number',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='surname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='deliverypricing',
            name='cost_per_kg',
            field=webstore.cash.fields.CashField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypricing',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deliverypricing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='deliverypricing',
            name='delivery_option',
        ),
        migrations.RemoveField(
            model_name='deliverypricing',
            name='max_param',
        ),
        migrations.RemoveField(
            model_name='deliverypricing',
            name='price',
        ),
        migrations.DeleteModel(
            name='DeliveryOption',
        ),
    ]
