# Generated by Django 2.0 on 2018-07-25 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20180718_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='delivery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
