# Generated by Django 2.0 on 2018-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'awaiting payment'), ('READY_FOR_SHIPPING', 'ready for shipping'), ('SHIPPED', 'shipped')], default='AWAITING_PAYMENT', max_length=32),
        ),
    ]
