# Generated by Django 2.0.2 on 2018-02-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_auto_20180205_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('payed', models.BooleanField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
