# Generated by Django 2.0.2 on 2018-08-12 13:17

from django.db import migrations, models
import django.db.models.deletion
import webstore.cash.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('payed', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('cr', 'card'), ('tr', 'transfer'), ('ud', 'upon delivery')], default='tr', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('DELAYED', 'delayed'), ('CLOSED', 'closed')], default='OPEN', max_length=16)),
                ('value', webstore.cash.fields.CashField(max_length=32)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
