# Generated by Django 2.0.2 on 2018-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cr', 'card'), ('tr', 'transfer'), ('ud', 'upon delivery')], default='tr', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
