# Generated by Django 2.1.3 on 2019-01-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20181224_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='modified',
            new_name='edited',
        ),
    ]
