# Generated by Django 2.0 on 2018-07-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('DELAYED', 'delayed'), ('CLOSED', 'closed')], default='OPEN', max_length=16),
        ),
    ]
