# Generated by Django 2.1.3 on 2019-01-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190101_2234'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payment_pay_order_i_211f02_idx'),
        ),
    ]
