# Generated by Django 2.0.2 on 2018-08-12 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import webstore.cash.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'ordering': ['product', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('data', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', webstore.cash.fields.CashField(help_text='returns instance of Cash', max_length=32)),
                ('valid_from', models.DateField(default=datetime.date.today, help_text='helps to determine which price is valid at moment of runtime')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(default='description not available')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(default=0, help_text='weight in kg')),
                ('width', models.FloatField(default=0, help_text='width in cm')),
                ('height', models.FloatField(default=0, help_text='height in cm')),
                ('length', models.FloatField(default=0, help_text='length in cm')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Category')),
                ('picture', models.ManyToManyField(through='product.Gallery', to='product.Picture')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Picture'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('product', 'number')},
        ),
    ]
