# Generated by Django 2.0.2 on 2018-12-15 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='picture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
