# Generated by Django 2.0.2 on 2018-02-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=0, help_text='height in cm'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=0, help_text='length in cm'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, help_text='weight in kg'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0, help_text='width in cm'),
        ),
    ]
