# Generated by Django 2.0.2 on 2018-08-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180826_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
