# Generated by Django 2.1.3 on 2018-12-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181215_0130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('picture', 'product'), ('product', 'number')},
        ),
    ]
