# Generated by Django 2.0.2 on 2018-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180325_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['product', '-number'], 'verbose_name': 'Gallery Image'},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='data',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
