# Generated by Django 2.0.2 on 2018-11-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='returns instance of Cash', max_digits=8),
        ),
    ]
