# Generated by Django 2.1.3 on 2018-12-24 21:19

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181223_2216'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['valid_from'], name='product_pri_valid_f_862ca5_brin'),
        ),
    ]
