# Generated by Django 2.0 on 2018-11-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181101_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
