# Generated by Django 2.0.2 on 2018-03-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180325_1841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('product', 'number')},
        ),
    ]
