# Generated by Django 2.1.3 on 2018-12-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181224_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='price',
            name='promo_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
