# Generated by Django 2.0.2 on 2018-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
