# Generated by Django 2.0 on 2018-02-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180205_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('confirmed', 'confirmed'), ('paid', 'paid'), ('shipped', 'shipped')], max_length=32),
        ),
    ]
