# Generated by Django 2.0.2 on 2018-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'awaiting payment'), ('SHIPPING', 'shipping'), ('CLOSED', 'closed'), ('CANCELLED', 'cancelled')], default='AWAITING_PAYMENT', max_length=32),
        ),
    ]
