# Generated by Django 2.0 on 2018-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180725_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'awaiting payment'), ('PREPADING_SHIPMENT', 'preparing shipment'), ('CLOSED', 'closed')], default='AWAITING_PAYMENT', max_length=32),
        ),
    ]
