# Generated by Django 2.0.2 on 2018-07-03 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.Session'),
        ),
    ]
