# Generated by Django 2.0.1 on 2018-01-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180129_2218'),
        ('cart', '0002_auto_20180107_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
