# Generated by Django 2.0.2 on 2018-07-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180703_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.Session'),
            preserve_default=False,
        ),
    ]
