# Generated by Django 2.0.2 on 2018-07-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180703_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(max_length=256),
        ),
    ]
