# Generated by Django 2.0.2 on 2018-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180703_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
