# Generated by Django 2.1.3 on 2018-12-26 23:54

from django.db import migrations
import webstore.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', webstore.users.models.CustomUserManager()),
            ],
        ),
    ]
